### ISSUE TITLE
no database

### ISSUE THREAD

**Issue by lokilust** [cypnk/Firewall#1]
How do i get it to work. it says
// Location of your database file (based on relative path)
// This will be where Firewall creates a SQLite database
define( 'FIREWALL_DB', 
	\realpath( \dirname( __FILE__ ) ) . '/data/firewall.db' );

but i do not see the file or folder ?

**Comment by cypnk** [comment]
Hi sorry, for the late reply. You can create the /data folder and give it chmod 0755 permissions and the database will be automatically created. This is optional and will only work if FIREWALL_DB_LOG is set to 1 (default)
