### ISSUE TITLE
Issue with header accept.

### ISSUE THREAD

**Issue by BlogSafe** [cypnk/Firewall#2]
First, thanks for this code!  I'm working on adapting it into a WordPress plugin and have it working for the most part.

One minor issue I ran into early is this:

```
	if ( !\array_key_exists( 'accept', $val ) ) {
		return true;
	}
```

It was finding a number of headers without the accept.  Some would have accept-encoding instead. From what I understand with RFC 2616 here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.

So, I've commented that out.

Thanks again.

**Comment by cypnk** [comment]
Hi, thanks for using this. 

I have added the accept-encoding check to cover both cases. I use the [plugin version](https://github.com/cypnk/Bare-Plugins/tree/master/firewall) of this on my Tor blog. Tor is a very hostile environment to run any software, let alone a blog, and very few clients use it so I tend to discard most traffic by default and didn't consider accept-encoding.

Thanks again.
